version: '3.9'

services:
  frontend:
    image: nginx:alpine
    volumes:
      - ./frontend:/usr/share/nginx/html:ro
    ports:
      - "8000:80"
    depends_on:
      - api
    networks:
      - frontend

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=${NODE_ENV}
      - DB_HOST=user-db
      - DB_PORT=27017
      - DB_USER=${MONGO_INITDB_ROOT_USERNAME}
      - DB_PASS=${MONGO_INITDB_ROOT_PASSWORD}
      - DB_NAME=${MONGO_DB_NAME}
    ports:
      - "${PORT}:5000"
    depends_on:
      - user-db
    networks:
      - frontend
      - backend

  user-db:
    image: mongo:6
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - user_data:/data/db
    networks:
      - backend

volumes:
  user_data:

networks:
  frontend:
  backend:
